ignore_files = {
    'abracadabra',
    'acc',
    'alphabetical',
    'anagram',
    'androids',
    'answer',
    'ascii',
    'authors',

    'bfs',
    'blank',
    'bnnaccuracy',
    'boolean',
    'branches',
    'breadthfirstsearch',
    'brutebrute',
    'build',
    'buildwiki',

    'c++',
    'cakeytest',
    'calendar',
    'canofbeans',
    'cardsim',
    'carryoperation',
    'casual',
    'cesta',
    'check',
    'chemistry',
    'commentsoncs',
    'comp',
    'completed',
    'contest4solutions',

    'datetime',
    'deque',
    'dice',
    'directoryreader',
    'discreteutils',
    'djikstra',
    'duplicates',

    'easy',
    'eksempelinput',
    'eksempeloutput',
    'emoto',
    'error',
    'examplegameclient',

    'fahrenheit',
    'food',

    'generatereadme',
    'getallproblems',
    'getyerarmorhere',
    'golomb',

    'happytrails',
    'hard',
    'hextodecimal',

    'in',
    'incomplete',
    'info',
    'input',
    'iterm',

    'java',
    'jbuild',
    'jtest',

    'kattio',
    'kattis',

    'lambdas',
    'lap',
    'license',

    'main',
    'makefile',
    'matrixmult',
    'maxflowdinic',
    'medium',
    'melzarsmaze',
    'monstertruck',

    'neolexicographicordering',
    'node',

    'old',
    'oops',
    'openkattis',
    'output',

    'pair',
    'pairstack',
    'parsing',
    'peanuts',
    'perfectnumber',
    'pingpong',
    'plantina',
    'point',
    'point2d',
    'polynomial',
    'primedrive',
    'programmingpractice',
    'psenica',
    'public',
    'pysum',
    'pytest',
    'python',

    'readmegenerator',
    'reverse',
    'romannumbers',
    'runcmd',
    'runningrace',

    'scanner',
    'schedule',
    'scrapper',
    'script',
    'secret',
    'setup',
    'setupcpp',
    'setuppython',
    'setuppythontestgen',
    'smallinput',
    'sol',
    'solution',
    'solutions',
    'src',
    'sticky',
    'stringhashing',
    'submit',
    'swaptwonumbers',

    'tempcoderunnerfile',
    'template',
    'test',
    'tester',
    'testgen',
    'testingtool',
    'tetest',
    'threads',
    'timecomplexity',
    'tle',
    'tplate',
    'trie',
    'txtenc',

    'util',
    'utils',

    'vaccination',
    'version',
    'vimrc',
    'voting',

    'wcfd',
    'weightedgraph',
    'why',
    'wordsearchgame',
    'wordsearchgamefactory',
    'wronganswer',

    'zodiac',
    'updatedocs',
    'encoding',
    'shut',
}
