name_mappings = {
    'twok': '2048',

    '3dprintedstatues': '3dprinter',

    'fourthought': '4thought',

    'eightqueens': '8queens',
    '8queen': '8queens',

    'ninetynineproblems': '99problems2',

    '10kind': '10kindsofpeople',
    'tenkindsofpeople': '10kindsofpeople',
    '10kindsofpeoplenaive': '10kindsofpeople',

    'arealchallenge': 'areal',
    'addemupvariations': 'addemup',
    'absurdistan2hc': 'absurdistan2',
    'armystrengthhardshortcut': 'armystrengthhard',
    'a1paperbetter': 'a1paper',
    'airconditionedminions': 'airconditioned',
    'anthonyandcora': 'anthony',
    'aliceinthedigitalworld': 'alicedigital',
    'fallingapples': 'apples',
    'autoriregex': 'autori',
    'administrativedifficulties': 'administrativeproblems',
    'amalgamatedartichokes': 'artichoke',
    'artichokes': 'artichoke',
    'aboveavg': 'aboveaverage',
    'aliennum': 'aliennumbers',
    'asciiadd': 'asciiaddition',
    'asciifig': 'asciifigurerotation',
    'acmcontestscoring': 'acm',
    'anotherbrickinthewall': 'anotherbrick',
    'paradoxwithaverages': 'averageseasy',
    'apaxiaaaaaaaaaaaans': 'apaxiaaans',

    'base2pali': 'base2palindrome',
    'bestcompressionever': 'bestcompression',
    'brexitnegotations': 'brexitnegotiations',
    'bet': 'betting',
    'basicprogramming2v2': 'basicprogramming2',
    'explodingbatteries': 'batteries',
    'bmped': 'bumped',
    'bankqueue': 'bank',
    'thestockmarket': 'borsen',
    'balnceddiet': 'balanceddiet',
    'acccounting': 'bokforing',
    'accounting': 'bokforing',
    'deliciousbubbletea': 'bubbletea',
    'babyloniannumbers': 'babylonian',
    'ballotbox': 'ballotboxes',

    'coastlength': 'coast',
    'coldputerscience': 'cold',
    'afuriouscocktail': 'cocktail',
    'coconutsplat': 'coconut',
    'codtosavelives': 'codetosavelives',
    'checkforcorrectness': 'checkingforcorrectness',
    'canvaspainting': 'canvas',
    'choppingwood': 'chopwood',
    'cardtrick': 'cardtrick2',
    'cardtrickhardcode': 'cardtrick2',
    'chemistvows': 'chemistsvows',
    'satelite': 'communicationssatellite',
    'buyingcoke': 'coke',
    'bestcompromise': 'compromise',
    'catalannumbers': 'catalan',
    'jumbledcommunication': 'communication',
    'characterdevelopment': 'character',
    'coloringsocks': 'color',
    'aclassyproblem': 'classy',
    'cprnumber': 'cprnummer',
    'compress': 'dictionary',

    'digitaldisplay': 'display',
    'divyingup': 'divvyingup',
    'digitproduct': 'sifferprodukt',
    'drm': 'drmmessages',
    'digraph': 'digraphs',
    'dungeonmaster': 'dungeon',
    'adifferentproblem': 'different',
    'dicebet': 'dicebetting',
    'divisiblesubsequences': 'divisible',
    'dartscore': 'dartscores',

    'exactlyeletrical': 'exactlyelectrical',
    'ecoin': 'ecoins',
    'emagehethtiwempleh': 'empleh',
    'evenorodd': 'evenodd',

    'factstonenomath': 'factstone',
    'fire': 'fire2',
    'freefod': 'freefood',
    'fiftyshadesofpink': 'fiftyshades',
    'ftrails': 'flowerytrails',
    'fbiuniversalcontrolnumbers': 'fbiuniversal',
    'fantasydrafticpc': 'fantasydraft',
    'favorableending': 'favourable',
    'firestationmst': 'firestation',
    'continuedfraction': 'fraction',
    'fastfoodprizes': 'fastfood',
    'birthdaymemorization': 'fodelsedagsmemorisering',
    'fallingmugs': 'falling',

    'greetingcards': 'greetingcard',
    'goldbach': 'goldbach2',
    'goldbachsconjecture': 'goldbach2',
    'guesstheds': 'guessthedatastructure',
    'guessthenumber': 'guess',
    'gettinggold': 'gold',
    'thegourmet': 'gourmeten',

    'helloworld': 'hello',
    'horrorlist': 'horror',
    'watchoutforthosehailstones': 'hailstone',
    'hailstonesequences': 'hailstone2',
    'happyhappyprimeprime': 'happyprime',
    'helpmewiththegame': 'helpme',
    'humancannonballrun': 'humancannonball',
    'hamiltonianhypercube': 'hypercube',

    'icpawards': 'icpcawards',
    'includesorting': 'includescoring',
    'wheresmyinternet': 'internet',
    'treeinsertion': 'insert',
    'ithqueen': 'ith',
    'ignorethegarbage': 'ignore',
    'anindustrialspy': 'industrialspy',

    'jolly': 'jollyjumpers',
    'joinattack': 'jointattack',

    'kingsofforest': 'knigsoftheforest',

    'alistgame': 'listgame',
    'keystrokes': 'lyklagangriti',
    'longestincreasingsubsequence': 'longincsubseq',
    'limbopart': 'limbo1',
    'dragonloowater': 'loowater',
    'thedragonofloowater': 'loowater',

    'penguins': 'marchofpenguins',
    'mubuda': 'mububa',
    'maximumrentgraphical': 'maximumrent',
    'maximumrentbigm': 'maximumrent',
    'mirrorimages': 'mirror',
    'themazemakers': 'mazemakers',
    'matrixinverse': 'matrix',
    'imperialmeasurement': 'measurement',
    'themailboxmanufacturersproblem': 'mailbox',
    'mosquitomultiplication': 'mosquito',
    'minimumscalarproduct': 'minimumscalar',

    'noduplicates': 'nodup',
    'ihatethenumbernine': 'nine',
    'ihatethenumber': 'nine',
    'ihatenine': 'nine',

    'oddsofmia': 'odds',
    'restaurantorders': 'orders',
    'onechickenperperson': 'onechicken',
    'oddbinomialcoefficients': 'oddbinom',
    'theowlandthefox': 'owlandfox',

    'planestrainsnotautos': 'planestrainsbutnotautomobiles',
    'polynomialmultiplication': 'polymul1',
    'polymul': 'polymul1',
    'pizzacrust': 'pizza2',
    'polishnotation': 'polish',
    'popcorn': 'popkorn',
    'perfectpth': 'perfectpowers',
    'pseudoprimenumbers': 'pseudoprime',

    'quadrantselection': 'quadrant',

    'reversedbinary': 'reversebinary',
    'reversedbinarynumbers': 'reversebinary',
    'workreduction': 'reduction',
    'robotinmaze': 'robotmaze',
    'rdecimals': 'repeatingdecimal',
    'registerslowpoke': 'register',
    'whitewaterrafting': 'rafting',
    'therectanglesaresurroundingus': 'rectanglesurrounding',

    'shortestpath': 'shortestpath1',
    'silkar': 'slikar',
    'snapperchainhard': 'snapperhard',
    'retirement': 'savingforretirement',
    'ebaltosaxophoneplayer': 'saxophone',
    'sodasurpler': 'sodaslurper',
    'stirlingsaprox': 'stirlingsapproximation',
    'sperhling': 'spehrling',
    '01seq': 'sequences',
    '01sequences': 'sequences',
    'squawkvirus': 'squawk',
    'songbook': 'sangbok',
    'linesegment': 'segmentdistance',
    'shufflingalong': 'shuffling',

    'imthinkingofanumber': 'thinkingofanumber',
    'timetravellingtemperatures': 'temperature',
    'toiletseat': 'toilet',
    'taisform': 'taisformula',
    'busskortet': 'thebuscard',
    'texturanalysis': 'textureanalysis',
    'thisaintyourgrandpas': 'thisaintyourgrandpascheckerboard',
    'trianglearea': 'triarea',
    'tunnellingtheearth': 'tunnelingtheearth',
    'taketwostones': 'twostones',
    'torntopieces': 'torn2pieces',
    'atoweringproblem': 'towering',
    'sierpinskicircumference': 'triangle',
    'sierpińskicircumference': 'triangle',
    'töflur': 'toflur',
    'towerconstruction': 'tornbygge',
    'stuckinatimeloop': 'timeloop',
    'icpctutorial': 'tutorial',

    'rightofway': 'vajningsplikt',
    'virusrep': 'virus',

    'welcometocodejam': 'welcomeeasy',
    'fox': 'whatdoesthefoxsay',
    'internet': 'wheresmyinternet',
    'wheel': 'wheels',
    'whichbaseisit': 'whichbase',
    'whichbaseisitanyway': 'whichbase',
    'wipewhiteboard': 'wipeyourwhiteboards',
    'wordcloudsrevisited': 'wordclouds',
    'assigningworkstations': 'workstations',
    'theweightofwords': 'weightofwords',

    'xenotopia': 'xentopia',

    'yinandyangstones': 'yinyangstones',

    'zebraocelots': 'zebrasocelots',
    'zebrasandocelots': 'zebrasocelots',
    'zigzagnametag': 'zigzag',
    'zipfssong': 'zipfsong',
    'unbearablezoo': 'zoo',
}
