name_mappings = {
    '10kind': '10kindsofpeople',
    'tenkindsofpeople': '10kindsofpeople',
    '10kindsofpeoplenaive': '10kindsofpeople',
    '10kindsofpeoplelabelling': '10kindsofpeople',
    '10kindsofpeopleufds': '10kindsofpeople',
    '1dfrog': '1dfroggereasy',
    'onedfrogger': '1dfroggereasy',
    'onedfroggerhard': '1dfroggerhard',
    'onedfroggerhardtwo': '1dfroggerhard',

    'twok': '2048',
    '2048shorter': '2048',
    'twentyfortyeight': '2048',
    'twofoursixgreat': '246greaaat',

    'printer': '3dprinter',

    'fourthought': '4thought',

    '99probs': '99problems',
    'ninetynineproblems': '99problems2',

    'a1paperdp': 'a1paper',
    'a1paperbetter': 'a1paper',
    'aboveavg': 'aboveaverage',
    'absurdistan2hc': 'absurdistan2',
    'absurdistan': 'absurdistan2',
    'acmscoring': 'acm',
    'addemupvariations': 'addemup',
    'addwords': 'addingwords',
    'addingswords': 'addingwords',
    'adjoinnetworks': 'adjoin',
    'agamemnonodyssey': 'agamemnonsodyssey',
    'agamemnonodysseydp': 'agamemnonsodyssey',
    'agariodag': 'agario',
    'agariorecurisive': 'agario',
    'agariotestcasegenerator': 'agario',
    'airconminions': 'airconditioned',
    'aliennum': 'aliennumbers',
    'allaboutbase': 'allaboutthatbase',
    'apsp': 'allpairspath',
    'almostuf': 'almostunionfind',
    'almostonion': 'almostunionfind',
    'alturisticamphibians': 'altruisticamphibians',
    'shebaamoebas': 'amoebas',
    'amsterdam': 'amsterdamdistance',
    'anagramcount': 'anagramcounting',
    'oceansanti': 'anti11',
    'anti11easy': 'anti11',
    'oceanshard': 'anti11hard',
    'antiarihmetic': 'antiarithmetic',
    'apaxiaaaaaaaaaaaans': 'apaxiaaans',
    'apaxiaaaaaans': 'apaxiaaans',
    'axpaxia': 'apaxiaaans',
    'honourthyparent': 'apaxianparent',
    'arrayoothening': 'arraysmoothening',
    'armystrength': 'armystrengtheasy',
    'armystrengthhardshortcut': 'armystrengthhard',
    'asciiadd': 'asciiaddition',
    'asciifig': 'asciifigurerotation',
    'asciifigure': 'asciifigurerotation',
    'atrologicalsign': 'astrologicalsign',
    'autotrading': 'automatictrading',
    'autoriregex': 'autori',
    'paradoxavg': 'averageseasy',
    'avoidapocalypse': 'avoidingtheapocalypse',

    'babylon': 'babylonian',
    'baconeggsspam': 'baconeggsandspam',
    'balnceddiet': 'balanceddiet',
    'ballotbox': 'ballotboxes',
    'base2pali': 'base2palindrome',
    'basicprogramming2v2': 'basicprogramming2',
    'basketballoneononelonger': 'basketballoneonone',
    'basketballoneoneone': 'basketballoneonone',
    'basketball': 'basketballoneonone',
    'battelsimulation': 'battlesimulation',
    'beatthespread': 'beatspread',
    'bet': 'betting',
    'bingit': 'bing',
    'acccounting': 'bokforing',
    'brexitnegotations': 'brexitnegotiations',
    'bmped': 'bumped',
    'busnum': 'busnumbers',

    'cakemccakeface': 'cakeymccakeface',
    'cantibable': 'cantinaofbabel',
    'cardtrickhardcode': 'cardtrick2',
    'catvs': 'catvsdog',
    'chanukachallenge': 'chanukah',
    'chanukahchellenge': 'chanukah',
    'checkforcorrectness': 'checkingforcorrectness',
    'chemistvows': 'chemistsvows',
    'chocolatedivison': 'chocolatedivision',
    'furiouscocktail': 'cocktail',
    'codtosavelives': 'codetosavelives',
    'satelite': 'communicationssatellite',
    'communicationssattelite': 'communicationssatellite',
    'cookieselectionpq': 'cookieselection',
    'computingmachinery': 'cool1',
    'cprnumber': 'cprnummer',
    'croptriangles': 'cropeasy',
    'cutinlinelinkedlist': 'cutinline',

    'blinkenlights': 'dasblinkenlights',
    'dicebet': 'dicebetting',
    'compress': 'dictionary',
    'distractedarrayadjlist': 'distracted',
    'distractedba': 'distracted',
    'distractedht': 'distracted',
    'divyingup': 'divvyingup',
    'keepthedogsapart': 'dogs',
    'drm': 'drmmessages',
    'drunkvignere': 'drunkvigenere',

    'ebonyivory': 'ebonyandivory',
    'echo': 'echoechoecho',
    'emagehethtiwempleh': 'empleh',
    'estimatingtheareaofcircle': 'estimatingtheareaofacircle',
    'evenorodd': 'evenodd',
    'beeneverywhereman': 'everywhere',
    'everywhereman': 'everywhere',
    'exactlyeletrical': 'exactlyelectrical',

    'factstonenomath': 'factstone',
    'fantasydrafticpc': 'fantasydraft',
    'favorableending': 'favourable',
    'afavorableending': 'favourable',
    'fibonaccisums': 'fibonaccisum',
    'fshades': 'fiftyshades',
    'fire3levelsearch': 'fire3',
    'firestationmst': 'firestation',
    'fleaonchessboard': 'fleaonachessboard',
    'ftrails': 'flowerytrails',
    'fractionalallotion': 'fractionallotion',
    'freefod': 'freefood',
    'atob': 'fromatob',
    'fruitsbasket': 'fruitbaskets',
    'fundamental': 'fundamentalneighbors',

    'goblinguards': 'goblingardenguards',
    'goldbach': 'goldbach2',
    'grassseedinc': 'grassseed',
    'grasseedinc': 'grassseed',
    'greedilyincreasingseubsequence': 'greedyincreasingsubsequences',
    'guesstheds': 'guessthedatastructure',

    'watchoutforthosehailstones': 'hailstone',
    'halfacircle': 'halfacookie',
    'happyhappyprime': 'happyprime',
    'helloworld': 'hello',
    'helpaphdcandidateout': 'helpaphd',
    'helpaphdcandidate': 'helpaphd',
    'heritagegenerator': 'heritage',
    'hissing': 'hissingmicrophone',
    'semiprime': 'hnumbers',
    'holeynqueens': 'holeynqueensbatman',
    'horrorfilm': 'horrorfilmnight',
    'amazinghumancannonball': 'humancannonball',
    'humancanonball': 'humancannonball',
    'huntthewampus': 'huntthewumpus',

    'toolbar': 'icons',
    'icpawards': 'icpcawards',
    'imagedecoder': 'imagedecoding',
    'importspaghettitle': 'importspaghetti',
    'includesorting': 'includescoring',
    'integerdeivision': 'integerdivision',
    'internalcover': 'intervalcover',
    'ithqueen': 'ith',

    'jackandjillcd': 'jackjill',
    'janitor': 'janitortroubles',
    'joinattack': 'jointattack',
    'jolly': 'jollyjumpers',
    'judgingamoose': 'judgingmoose',

    'kattisquestrbt': 'kattissquest',
    'kingsofforest': 'knigsoftheforest',

    'lessvs': 'lessvsfewer',
    'limbopart': 'limbo1',
    'locust': 'locustlocus',
    'dragonloowater': 'loowater',
    'dragonofloowater': 'loowater',

    'magicalknights': 'magicalmysteryknight',
    'meowth': 'makingameowth',
    'penguins': 'marchofpenguins',
    'maximumnumberofcollinearpoints': 'maxcolinear',
    'maximumrentgraphical': 'maximumrent',
    'maximumrentbigm': 'maximumrent',
    'metronomecs': 'metronome',
    'craftingmines': 'minecraftdungeons',
    'binaryneuralnetwork': 'mnist2class',
    'travellingmonk': 'monk',
    'mooglegen': 'moogle',
    'mubuda': 'mububa',

    'nasty': 'nastyhacks',
    'ihatethenumber': 'nine',
    'ihatenine': 'nine',
    'hatenine': 'nine',
    'nin': 'nine',
    'nonboring': 'nonboringsequences',
    'nonprimefactorsfast': 'nonprimefactors',
    'nonprimefactorsslow': 'nonprimefactors',

    'oddevenzeroes': 'oddandevenzeroes',
    'olderbro': 'olderbrother',
    'onaveragetheyarepurple': 'onaveragetheyrepurple',
    'onechickenperperson': 'onechicken',
    'ostgoska': 'ostgotska',

    'patuljici': 'patuljci',
    'perfectpth': 'perfectpowers',
    'pickingupstickefficient': 'pickupsticks',
    'pickingupsticks': 'pickupsticks',
    'planestrainsnotautos': 'planestrainsbutnotautomobiles',
    'polynomialmultiplication': 'polymul1',
    'polymul': 'polymul1',
    'popcorn': 'popkorn',
    'powersoftwoeasy': 'powersof2easy',
    'goodcuberoot': 'prettygoodcuberoot',
    'princesspeachdat': 'princesspeach',

    'verifythis': 'queens',

    'randomdigitexpo': 'randomdigitalexponentiation',
    'therectanglesaresurroundingus': 'rectanglesurrounding',
    'rectsurround': 'rectanglesurrounding',
    'growingspiral': 'rectangularspiral',
    'redbluespanningtree': 'redbluetree',
    'registerslowpoke': 'register',
    'rdecimals': 'repeatingdecimal',
    'workingatarest': 'restaurant',
    'reversedbinary': 'reversebinary',
    'robotgrid': 'robotsonagrid',
    'robotinmaze': 'robotmaze',
    'mom': 'runningmom',
    'runingmom': 'runningmom',
    'runningmomslow': 'runningmom',

    'retirement': 'savingforretirement',
    'linesegment': 'segmentdistance',
    'serverkattis': 'server',
    'divdingsequence': 'sequence',
    '01seq': 'sequences',
    'zeroonesequences': 'sequences',
    'shortestpath': 'shortestpath1',
    'ssshortestpathnonneg': 'shortestpath1',
    'shortestpath3dfs': 'shortestpath3',
    'digitalproduct': 'sifferprodukt',
    'sjectica': 'sjecista',
    'gointoschool': 'skolvagen',
    'silkar': 'slikar',
    'snapper': 'snappereasy',
    'sodasurpler': 'sodaslurper',
    'spidermanworkout': 'spiderman',
    'squarefields': 'squarefieldseasy',
    'squarepegroundhole': 'squarepegs',
    'sredjni': 'srednji',
    'stirlingsaprox': 'stirlingsapproximation',
    'streamingstats': 'streamstats',
    'subseqhardoptimised': 'subseqhard',
    'sumkindproblem': 'sumkindofproblem',
    'sumsquaredigit': 'sumsquareddigits',
    'symetricorder': 'symmetricorder',
    'synchronisinglists': 'synchronizinglists',

    'taisform': 'taisformula',
    'ternarian': 'ternarianweights',
    'texturanalysis': 'textureanalysis',
    'kingofthenorth': 'thekingofthenorth',
    'thisaintyourgrandpas': 'thisaintyourgrandpascheckerboard',
    'tolfur': 'toflur',
    'towersofpowers2powerharder': 'towers',
    'bumper': 'traffic',
    'sierpinskicircumference': 'triangle',
    'twocharts': 'twochartsbecomeone',

    'undeadalive': 'undeadoralive',

    'virusrep': 'virus',
    'visualpython': 'visual',
    'volumeamplify': 'volumeamplification',

    'weighlifting': 'weightlifting',
    'welcometocodejam': 'welcomeeasy',
    'fox': 'whatdoesthefoxsay',
    'whatsinitforme': 'whatsinit',
    'internet': 'wheresmyinternet',
    'wheremyinternet': 'wheresmyinternet',
    'whereismyinternet': 'wheresmyinternet',
    'whichbaseisit': 'whichbase',
    'whichbaseisitanyway': 'whichbase',
    'wipewhiteboard': 'wipeyourwhiteboards',
    'wizzardofodds': 'wizardofodds',
    'workoutfordumbell': 'workout',

    'xenotopia': 'xentopia',

    'yingandyangstones': 'yinyangstones',

    'zebraocelots': 'zebrasocelots',
    'zyxabb': 'zyxab',
}
